---

- name: Download Aerospike server
  get_url:
    url: "{{ aerospike_server_url }}"
    dest: "/tmp/{{ aerospike_server_pkg }}.tgz"

- name: Unarchive Aerospike server
  unarchive:
    src: "/tmp/{{ aerospike_server_pkg }}.tgz"
    dest: /tmp/
    remote_src: yes

- name: Install Aerospike server
  shell: ./asinstall
  args:
    chdir: "/tmp/{{ aerospike_server_pkg }}"
    creates: /etc/init.d/aerospike

- name: Start Aerospike server
  service: name=aerospike state=started enabled=true

- name: Put aerospike.conf
  template:
    src=aerospike.conf
    dest=/etc/aerospike/aerospike.conf
  notify: Restart Aerospike
